Task5
ozoncp/ocp-contact-api pull request #6
Opened 2021-08-09 00:13 UTC by echekunov

- saver implementation
- added tests for the Saver

2021-08-09 09:46 UTC, kshmatov requested changes

2021-08-09 09:46 UTC, kshmatov commented on internal/saver/saver.go
> +	s.close <- struct{}{}
Saver.Close предполагается для вызова один раз (у нас нет средств снова запустить горутину), поэтому здесь идиоматичнее не писать в s.close(), а просто закрыть его. И, соответственно, убрать закрытие из defer. Закрытие канала приводит к считыванию пустого значения из него.

2021-08-09 09:46 UTC, kshmatov commented on internal/saver/saver.go
> +		for {
Какой приоритет у операций? Сейчас возможна ситуация когда ничего не будет сохранено и не возможно будет закрыть Saver, потому что попытки чтения в каждом цикле выполняются сверху вниз. Если постоянно будут данные, то они будут съедать каждый цикл.

2021-08-09 09:46 UTC, kshmatov commented on internal/saver/saver.go
> +func (s *saver)Save(contact models.Contact) {
Что случится, если сначала выполнить Saver.Close(), а потом Saver.Save() ?

2021-08-09 22:30 UTC, echekunov commented on internal/saver/saver.go
> +	s.close <- struct{}{}
поправил

2021-08-09 22:33 UTC, echekunov commented on internal/saver/saver.go
> +		for {
Сделал канал не буферизированным. Так проще управлять.

2021-08-09 22:33 UTC, echekunov commented on internal/saver/saver.go
> +func (s *saver)Save(contact models.Contact) {
Запретил паниковать:) Написал тест.

2021-08-10 08:12 UTC, kshmatov approved these changes

2021-08-10 08:23 UTC, merged